name: Build & Push to ECR

on:
  push:
    branches: [main]
  workflow_dispatch:  # allows manual trigger from GitHub UI

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 738245087422.dkr.ecr.us-east-2.amazonaws.com

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---- FastAPI API Image ----
      - name: Build & Push API image
        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/housing-regression-api:latest -t $ECR_REGISTRY/housing-regression-api:${{ github.sha }} .
          docker push $ECR_REGISTRY/housing-regression-api --all-tags

      # ---- Streamlit UI Image ----
      - name: Build & Push Streamlit image
        run: |
          docker build -f Dockerfile.streamlit -t $ECR_REGISTRY/housing-regression-streamlit:latest -t $ECR_REGISTRY/housing-regression-streamlit:${{ github.sha }} .
          docker push $ECR_REGISTRY/housing-regression-streamlit --all-tags
